language: node_js
node_js:
  - "0.10"
env:
  - DISPLAY=:99.0
addons: {apt: {sources: [ubuntu-toolchain-r-test], packages: [g++-4.9]}}
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - npm install casperjs
  - npm install typescript
  - wget -P /tmp/j2me.js -N https://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/37.0b7-candidates/build1/jsshell-linux-x86_64.zip
  - unzip -d /tmp/js /tmp/j2me.js/jsshell-linux-x86_64.zip
  - export PATH=$PATH:/tmp/js
  - git clone --recursive https://github.com/marco-c/emscripten-sdk.git && cd emscripten-sdk && ./emsdk activate latest && source ./emsdk_env.sh && cd ..
script:
  - make test
sudo: false
notifications:
  irc:
    channels:
      - "irc.mozilla.org#j2me.js"
    template:
      - "%{repository_slug} - %{commit_subject} - %{result} - %{build_url}"
    use_notice: true
    skip_join: true
