language: node_js
node_js:
  - "0.10"
env:
  - DISPLAY=:99.0
before_script:
  - "sh -e /etc/init.d/xvfb start"
  - npm install casperjs
  - wget -P /tmp/j2me.js -N https://ftp.mozilla.org/pub/mozilla.org/labs/j2me.js/slimerjs-0.10.0pre-2014-12-17.zip
  - unzip -d /tmp /tmp/j2me.js/slimerjs-0.10.0pre-2014-12-17.zip
  - export PATH=$PATH:/tmp/slimerjs-0.10.0pre
  - wget -P /tmp/j2me.js -N https://ftp.mozilla.org/pub/mozilla.org/xulrunner/releases/31.0/runtimes/xulrunner-31.0.en-US.linux-x86_64.tar.bz2
  - tar x -C /tmp -f /tmp/j2me.js/xulrunner-31.0.en-US.linux-x86_64.tar.bz2
  - export SLIMERJSLAUNCHER=/tmp/xulrunner/xulrunner
  - wget -P /tmp/j2me.js -N https://ftp.mozilla.org/pub/mozilla.org/firefox/nightly/36.0b1-candidates/build1/jsshell-linux-x86_64.zip
  - unzip -d /tmp/js /tmp/j2me.js/jsshell-linux-x86_64.zip
  - export PATH=$PATH:/tmp/js
script:
  - make test
sudo: false
cache:
  directories:
    - node_modules
    - /tmp/j2me.js
notifications:
  irc:
    channels:
      - "irc.mozilla.org#j2mejs"
    template:
      - "%{repository_slug} - %{commit_message} - %{result} %{message} - %{build_url}"
    use_notice: true
    skip_join: true
